package io.bitken.ss.ledger;

public enum EventType {
    TASK_REGISTRATION,
    STATUS_UPDATED,
    COMMENT_ADDED,
    DEVIATION_ADDED,
    COMMIT_RECORDED,
    PROJECT_UPDATE,
    AGENT_START,
    WORKTREE_CREATED,
    PATCH_EMITTED,
    CLEANUP,
    INTEGRATION_PLAN,
    PATCH_INTEGRATED,
    INTEGRATION_FAILURE,
    INTEGRATION_COMPLETE,
    RESOLVER_REQUESTED,
    RESOLVER_COMPLETE
}